/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as CobrosRouteImport } from './routes/cobros'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as BiRouteImport } from './routes/bi'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrosRoute = CobrosRouteImport.update({
  id: '/cobros',
  path: '/cobros',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/clientes': typeof ClientesRoute
  '/cobros': typeof CobrosRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/clientes': typeof ClientesRoute
  '/cobros': typeof CobrosRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/clientes': typeof ClientesRoute
  '/cobros': typeof CobrosRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bi'
    | '/clientes'
    | '/cobros'
    | '/cotizaciones'
    | '/dashboard'
    | '/inventario'
    | '/login'
    | '/reset-password'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bi'
    | '/clientes'
    | '/cobros'
    | '/cotizaciones'
    | '/dashboard'
    | '/inventario'
    | '/login'
    | '/reset-password'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/bi'
    | '/clientes'
    | '/cobros'
    | '/cotizaciones'
    | '/dashboard'
    | '/inventario'
    | '/login'
    | '/reset-password'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiRoute: typeof BiRoute
  ClientesRoute: typeof ClientesRoute
  CobrosRoute: typeof CobrosRoute
  CotizacionesRoute: typeof CotizacionesRoute
  DashboardRoute: typeof DashboardRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobros': {
      id: '/cobros'
      path: '/cobros'
      fullPath: '/cobros'
      preLoaderRoute: typeof CobrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiRoute: BiRoute,
  ClientesRoute: ClientesRoute,
  CobrosRoute: CobrosRoute,
  CotizacionesRoute: CotizacionesRoute,
  DashboardRoute: DashboardRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
